Updated register system.
Added database in 000webhost
Added php files in 000webhost

Error: org.json.JSONException: Value <br><table of type java.lang.String
cannot be converted to JSONObject